### ISSUE TITLE
some links seems incorrects

### ISSUE THREAD

**Issue by thib3113** [crowdsecurity/cs-custom-bouncer#21]
It seems recently the project was renamed from `crowdsec-custom-bouncer` to `cs-custom-bouncer` . 

So, In readme : 
 - logo image point to the incorrect repo
 - url to release point to the incorrect repo
 - From source : url of the git repo is incorrect, with all the request (not sure if github do a link to the new name)
 - start : command seems invalid (on my install, service name seems to be `cs-custom-bouncer.service` )
 - Upgrade : bad link to last release
 - Configuration : on my installation, config seems to be in `/etc/crowdsec/cs-custom-bouncer/cs-custom-bouncer.yaml` and not `/etc/crowdsec/bouncers/crowdsec-custom-bouncer.yaml` ( and so, not under `/etc/crowdsec/bouncers/` )
  - "You can then start the service:" : on my installation, service name seems to be `cs-custom-bouncer.service`

**Comment by AlteredCoder** [comment]
Hello @thib3113,

It's the opposite. The binary/service was renamed from `cs-custom-bouncer` to `crowdsec-custom-bouncer`. While renaming everything to `crowdsec-custom-bouncer` , we broke some links in the README since the github repository is still called `cs-custom-bouncer`.

About those points:
 - start : command seems invalid (on my install, service name seems to be cs-custom-bouncer.service )
 - "You can then start the service:" : on my installation, service name seems to be cs-custom-bouncer.service
 - Configuration : on my installation, config seems to be in /etc/crowdsec/cs-custom-bouncer/cs-custom-bouncer.yaml

On the latest release (v0.0.8), the service should be called `crowdsec-custom-bouncer` and the configuration folder/file should be called `crowdsec-custom-bouncer` also.

Can you confirm those points please?

I've also fixed the link in the README, is it good for you ?


Thanks :)

**Comment by thib3113** [comment]
Hum, ok, I see . 

I see I'm always in 0.0.6, and the upgrade.sh fail to work xD ... 

In fact the upgrade.sh fail successfully 😂 . 

```
root@docker-3:~/crowdsec-custom-bouncer-v0.0.8# ./upgrade.sh
Failed to stop crowdsec-custom-bouncer.service: Unit crowdsec-custom-bouncer.service not loaded.
rm: cannot remove '/usr/local/bin/crowdsec-custom-bouncer': No such file or directory
crowdsec-custom-bouncer is not installed, exiting.
'./crowdsec-custom-bouncer' -> '/usr/local/bin/crowdsec-custom-bouncer'
Failed to start crowdsec-custom-bouncer.service: Unit crowdsec-custom-bouncer.service not found.
crowdsec-custom-bouncer upgraded successfully.
root@docker-3:~/crowdsec-custom-bouncer-v0.0.8# /usr/local/bin/cs-custom-bouncer -h
INFO[0000] cs-custom-bouncer v0.0.6-35e98029f7de2e72eb41fd0a2f0d03d9768d7cfd
Usage of /usr/local/bin/cs-custom-bouncer:
  -c string
        path to cs-custom-bouncer.yaml
  -v    set verbose mode
```

I'll try to debug this later :) .

**Comment by AlteredCoder** [comment]
I think what you can do is : 

- Backup your configuration file : /etc/crowdsec/cs-custom-bouncer/cs-custom-bouncer.yaml
- Re download the cs-custom-bouncer v0.0.6
- Run the `uninstall.sh` script
- Download the cs-custom-bouncer v0.0.8
- Install it
- Copy your previous configuration file to `/etc/crowdsec/crowdsec-custom-bouncer/crowdsec-custom-bouncer.yaml`

Then start the service `sudo systemctl start crowdsec-custom-bouncer` .

**Comment by thib3113** [comment]
Hum, 

you say `/etc/crowdsec/crowdsec-custom-bouncer/crowdsec-custom-bouncer.yaml` but `/etc/crowdsec/crowdsec-custom-bouncer/` doesn't exist . Maybe a typo with `/etc/crowdsec/bouncers/crowdsec-custom-bouncer.yaml`

service fail to start with : 
```
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]: time="2021-07-29T13:20:26Z" level=info msg="crowdsec-custom-bouncer v0.0.8-4f818351921b3aed93f53da0f1f5d2fe12426fd6"
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]: panic: non-positive interval for NewTicker
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]: goroutine 1 [running]:
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]: time.NewTicker(0x0, 0x0)
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]:         /opt/hostedtoolcache/go/1.13.15/x64/src/time/tick.go:23 +0x147
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]: main.main()
juil. 29 13:20:26 docker-3 crowdsec-custom-bouncer[4517]:         /home/runner/work/cs-custom-bouncer/cs-custom-bouncer/main.go:96 +0x5fe
juil. 29 13:20:26 docker-3 systemd[1]: crowdsec-custom-bouncer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

conf : 
```
bin_path: /root/bouncer.sh
piddir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
api_url: ***
api_key: ***
```

**Comment by AlteredCoder** [comment]
`/etc/crowdsec/crowdsec-custom-bouncer/crowdsec-custom-bouncer.yaml` should exist after installing the v0.0.8. It is not the case ?

**Comment by thib3113** [comment]
ok I found, in the config : 
`cache_retention_duration: 10s` is mandatory, and not on the 0.0.6 :)

**Comment by buixor** [comment]
https://github.com/crowdsecurity/cs-custom-bouncer/pull/23 to handle a default value for `cache_retention_duration` that is now required.

**Comment by AlteredCoder** [comment]
cool ! @thib3113 is everything ok for you ? :) can we close this issue ?
