### ISSUE TITLE
-V flag to display bouncer version

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/cs-custom-bouncer#25]
Can we apply something like this? I thought this flag would be merged to all bouncers.
https://github.com/crowdsecurity/cs-firewall-bouncer/pull/41/commits/194c45fd814d41ba404f2c2a686ba0804687786d

To get only the version number is still not straight forward.
I use currently:
`crowdsec-custom-bouncer -v 2>&1 | grep level=info | sed -E "s/^.*v([0-9]+(\.[0-9]+)+)(.*\S.*)/\1/g"`

**Comment by LaurenceJJones** [comment]
Fixed in #31
