### ISSUE TITLE
crowdsec-custom-bouncer not available in packagecloud.io deb repositories

### ISSUE THREAD

**Issue by derfischi** [crowdsecurity/cs-custom-bouncer#47]
The crowdsec-custom-bouncer packages is not available in the offical packagecloud.io repositories for Ubuntu unlike stated in the official documentation.

https://doc.crowdsec.net/docs/bouncers/custom/#installation-from-packages

<pre>
root ~ # apt install crowdsec-custom-bouncer
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package crowdsec-custom-bouncer
</pre>

<pre>
root ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
</pre>

<pre>
root ~ # cat /etc/apt/sources.list.d/crowdsec_crowdsec.list
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/crowdsec/crowdsec

deb [signed-by=/usr/share/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ jammy main
deb-src [signed-by=/usr/share/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ jammy main
</pre>

**Comment by TonyRL** [comment]
Similar issue https://github.com/crowdsecurity/cs-blocklist-mirror/issues/18

Bouncers / packages which are available https://packagecloud.io/app/crowdsec/crowdsec/search?q=&filter=all&filter=all&dist=ubuntu%2Fjammy

**Comment by LaurenceJJones** [comment]
Triggered the build pipeline should be available via the repo within the next couple of hours.

**Comment by chladic** [comment]
Hi @LaurenceJJones. I still cant see it there, do you have any new estimate ?

**Comment by LaurenceJJones** [comment]
We are pending a new release soon, which should build for this.

**Comment by mmetc** [comment]
The pre-releases are at https://packagecloud.io/app/crowdsec/crowdsec-testing/search?dist=ubuntu%2Fjammy
