### ISSUE TITLE
Multiple add/del ban on start

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/cs-custom-bouncer#5]
Each time you start the custom-bouncer you get multiple time the same order.
On the restart this morning for me, I had 95 order for the exact same IP. (and you have a full list of IP with that).
Multiple time the exact same order, but with different ban time. 

time="10-12-2020 07:40:04" level=info msg="custom [/usr/local/bin/ban.php] : del ban on 180.253.162.196/32 for -509410 sec (crowdsecurity/http-path-traversal-probing)"
time="10-12-2020 07:41:04" level=info msg="custom [/usr/local/bin/ban.php] : del ban on 180.253.162.196/32 for -508364 sec (crowdsecurity/http-path-traversal-probing)"
time="10-12-2020 07:41:07" level=info msg="custom [/usr/local/bin/ban.php] : del ban on 180.253.162.196/32 for -508015 sec (crowdsecurity/http-path-traversal-probing)"

time="10-12-2020 07:45:45" level=info msg="custom [/usr/local/bin/ban.php] : add ban on 180.253.162.196/32 for 14799 sec (crowdsecurity/http-path-traversal-probing)"
time="10-12-2020 07:45:53" level=info msg="custom [/usr/local/bin/ban.php] : add ban on 180.253.162.196/32 for 21999 sec (crowdsecurity/http-path-traversal-probing)"
time="10-12-2020 07:45:59" level=info msg="custom [/usr/local/bin/ban.php] : add ban on 180.253.162.196/32 for 27311 sec (crowdsecurity/http-path-traversal-probing)"

To finally remove that ban : 
time="10-12-2020 07:40:04" level=info msg="custom [/usr/local/bin/ban.php] : del ban on 180.253.162.196/32 for -509410 sec (crowdsecurity/http-path-traversal-probing)"
time="10-12-2020 07:45:19" level=info msg="custom [/usr/local/bin/ban.php] : add ban on 180.253.162.196/32 for 399 sec (crowdsecurity/http-path-traversal-probing)"
time="10-12-2020 07:52:07" level=info msg="custom [/usr/local/bin/ban.php] : del ban on 180.253.162.196/32 for -323 sec (crowdsecurity/http-path-traversal-probing)"

Using a local cache to not execute the same order twice improve a lot the start time when you call some external API like cloudflare, but this should be done on the bouncer side.
This reduce the CPU usage too, but can probably be improved a lot if the bouncer don't send useless order from the begining.

Maybe make something like fail2ban.
On stop try to delete the actual active ban list.
On start only add new ban.
And maybe add some cscli decisions delete -time 48H or something like that, to force delete ban based on time to clear external ban list (like cloudflare).

[log.txt](https://github.com/crowdsecurity/cs-custom-bouncer/files/5670921/log.txt)

**Comment by LtSich** [comment]
Maybe add something in the config file to only redo the decisions on the last xx minutes.
And find some way to act differently on system reboot (reapply all ban for the last ban duration time), and on a "simple service restart" to only reapply the last xx minutes defined in the config file.

**Comment by Lamera** [comment]
I also have this issue here. There is something strange going on.

**Comment by buixor** [comment]
Hello, this should be fixed with the latest release : https://github.com/crowdsecurity/cs-custom-bouncer/releases/tag/v0.0.8
There is now a de-duplication mechanism for decisions, along with a cashing mechanism to avoid spamming when same IP triggers several scenarios in a row :+1:
