### ISSUE TITLE
Bouncer stop if the LAPI is down

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/cs-custom-bouncer#6]
If you restart the LAPI (in my case on a central node) the bouncer just stop working.
You got this message in log : 
time="10-12-2020 07:37:31" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
After that the process just stop.

You need to restart the bouncer (and go through the whole process on add/del ban).

This is really a problem on my setup. If I need to change the config on the central node, I have to restart all the bouncer on every servers. And use a lot of time to add/delete again the full ban list.

Maybe if the LAPI doesn't respond wait a little time, and retry connecting, maybe wait 1min or 2 and then restart the whole bouncer. But then we need some improvement on the process start to not use too much cpu time.

**Comment by AlteredCoder** [comment]
Hello @LtSich, sorry for the delay.
This issue was in the [go library](https://github.com/crowdsecurity/go-cs-bouncer) used by this bouncer to pull decisions from the crowdsec API. I've fixed the issue [here] and i'm now releasing a new version of this bouncer to update it.

**Comment by StrangePeanut** [comment]
Currently seem to experience this exact issue. Has this not been solved still?

Deployed CS in a Docker stack last night. Everything seemed to be fine but was surprised to see 0 active decisions this morning. Simulated a brute force and nothing is being added. Log reports `auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused` Upon restarting the firewall bouncer decisions are being received and dealt with once again.

**Comment by Staene** [comment]
I am experiencing this same issue. I can only assume that it originates from restarting crowdsec while a bouncer is running. If I don't also restart the bouncer, communication stays broken and decisions aren't applied.

I am using the Cloudflare-Worker-Bouncer.

**Comment by StrangePeanut** [comment]
> I am experiencing this same issue. I can only assume that it originates from restarting crowdsec while a bouncer is running. If I don't also restart the bouncer, communication stays broken and decisions aren't applied.
> 
> I am using the Cloudflare-Worker-Bouncer.

@Staene I have since discovered that the firewall bouncer would start too early in which case it would not listen to decisions. To work around the issue I disable the systemd service in favour of a timer to delay the start. I have not encountered the issue since. Hope this helps.
